services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    command: ["--auth", "--quiet"]
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

  # granitex:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: runner
  #   container_name: granitex
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_PORT: 27017
  #   ports:
  #     - 1323:1323
  #   networks:
  #     - mongodb_network
  #   depends_on:
  #     - mongodb

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
